export const cyberpunkConfig = {
  title: "Cyberpunk Portrait Collection",
  description: "Transform into a futuristic character with stunning cyberpunk-themed portraits perfect for gaming profiles and digital art",
  categories: [
    { name: 'All', value: 'all' },
    { name: 'Women', value: 'women' },
    { name: 'Men', value: 'men' }
  ],
  images: {
    women: [
      { src: '/Packs/Cyberpunk/Women/women1.jpg', alt: 'Cyberpunk woman portrait 1' },
      { src: '/Packs/Cyberpunk/Women/women2.jpg', alt: 'Cyberpunk woman portrait 2' },
      { src: '/Packs/Cyberpunk/Women/women3.jpg', alt: 'Cyberpunk woman portrait 3' },
      { src: '/Packs/Cyberpunk/Women/women4.jpg', alt: 'Cyberpunk woman portrait 4' },
      { src: '/Packs/Cyberpunk/Women/women5.jpg', alt: 'Cyberpunk woman portrait 5' },
      { src: '/Packs/Cyberpunk/Women/women6.jpg', alt: 'Cyberpunk woman portrait 6' },
      { src: '/Packs/Cyberpunk/Women/women7.jpg', alt: 'Cyberpunk woman portrait 7' },
      { src: '/Packs/Cyberpunk/Women/women8.jpg', alt: 'Cyberpunk woman portrait 8' },
      { src: '/Packs/Cyberpunk/Women/women9.jpg', alt: 'Cyberpunk woman portrait 9' },
      { src: '/Packs/Cyberpunk/Women/women10.jpg', alt: 'Cyberpunk woman portrait 10' },
      { src: '/Packs/Cyberpunk/Women/women11.jpg', alt: 'Cyberpunk woman portrait 11' },
      { src: '/Packs/Cyberpunk/Women/women12.jpg', alt: 'Cyberpunk woman portrait 12' },
      { src: '/Packs/Cyberpunk/Women/women13.jpg', alt: 'Cyberpunk woman portrait 13' },
      { src: '/Packs/Cyberpunk/Women/women14.jpg', alt: 'Cyberpunk woman portrait 14' },
      { src: '/Packs/Cyberpunk/Women/women15.jpg', alt: 'Cyberpunk woman portrait 15' },
      { src: '/Packs/Cyberpunk/Women/women16.jpg', alt: 'Cyberpunk woman portrait 16' },
      { src: '/Packs/Cyberpunk/Women/women17.jpg', alt: 'Cyberpunk woman portrait 17' },
      { src: '/Packs/Cyberpunk/Women/women18.jpg', alt: 'Cyberpunk woman portrait 18' },
      { src: '/Packs/Cyberpunk/Women/women19.jpg', alt: 'Cyberpunk woman portrait 19' },
      { src: '/Packs/Cyberpunk/Women/women20.jpg', alt: 'Cyberpunk woman portrait 20' },
      { src: '/Packs/Cyberpunk/Women/women21.jpg', alt: 'Cyberpunk woman portrait 21' },
      { src: '/Packs/Cyberpunk/Women/women22.jpg', alt: 'Cyberpunk woman portrait 22' },
      { src: '/Packs/Cyberpunk/Women/women23.jpg', alt: 'Cyberpunk woman portrait 23' },
      { src: '/Packs/Cyberpunk/Women/women24.jpg', alt: 'Cyberpunk woman portrait 24' },
      { src: '/Packs/Cyberpunk/Women/women25.jpg', alt: 'Cyberpunk woman portrait 25' },
      { src: '/Packs/Cyberpunk/Women/women26.jpg', alt: 'Cyberpunk woman portrait 26' },
      { src: '/Packs/Cyberpunk/Women/women27.jpg', alt: 'Cyberpunk woman portrait 27' },
      { src: '/Packs/Cyberpunk/Women/women28.jpg', alt: 'Cyberpunk woman portrait 28' },
      { src: '/Packs/Cyberpunk/Women/women29.jpg', alt: 'Cyberpunk woman portrait 29' },
      { src: '/Packs/Cyberpunk/Women/women30.jpg', alt: 'Cyberpunk woman portrait 30' },
    ],
    men: [
      { src: '/Packs/Cyberpunk/Man/man1.jpg', alt: 'Cyberpunk man portrait 1' },
      { src: '/Packs/Cyberpunk/Man/man2.jpg', alt: 'Cyberpunk man portrait 2' },
      { src: '/Packs/Cyberpunk/Man/man3.jpg', alt: 'Cyberpunk man portrait 3' },
      { src: '/Packs/Cyberpunk/Man/man4.jpg', alt: 'Cyberpunk man portrait 4' },
      { src: '/Packs/Cyberpunk/Man/man5.jpg', alt: 'Cyberpunk man portrait 5' },
      { src: '/Packs/Cyberpunk/Man/man6.jpg', alt: 'Cyberpunk man portrait 6' },
      { src: '/Packs/Cyberpunk/Man/man7.jpg', alt: 'Cyberpunk man portrait 7' },
      { src: '/Packs/Cyberpunk/Man/man8.jpg', alt: 'Cyberpunk man portrait 8' },
      { src: '/Packs/Cyberpunk/Man/man9.jpg', alt: 'Cyberpunk man portrait 9' },
      { src: '/Packs/Cyberpunk/Man/man10.jpg', alt: 'Cyberpunk man portrait 10' },
      { src: '/Packs/Cyberpunk/Man/man11.jpg', alt: 'Cyberpunk man portrait 11' },
      { src: '/Packs/Cyberpunk/Man/man12.jpg', alt: 'Cyberpunk man portrait 12' },
      { src: '/Packs/Cyberpunk/Man/man13.jpg', alt: 'Cyberpunk man portrait 13' },
      { src: '/Packs/Cyberpunk/Man/man14.jpg', alt: 'Cyberpunk man portrait 14' },
      { src: '/Packs/Cyberpunk/Man/man15.jpg', alt: 'Cyberpunk man portrait 15' },
      { src: '/Packs/Cyberpunk/Man/man16.jpg', alt: 'Cyberpunk man portrait 16' },
      { src: '/Packs/Cyberpunk/Man/man17.jpg', alt: 'Cyberpunk man portrait 17' },
      { src: '/Packs/Cyberpunk/Man/man18.jpg', alt: 'Cyberpunk man portrait 18' },
      { src: '/Packs/Cyberpunk/Man/man19.jpg', alt: 'Cyberpunk man portrait 19' },
      { src: '/Packs/Cyberpunk/Man/man20.jpg', alt: 'Cyberpunk man portrait 20' },
      { src: '/Packs/Cyberpunk/Man/man21.jpg', alt: 'Cyberpunk man portrait 21' },
      { src: '/Packs/Cyberpunk/Man/man22.jpg', alt: 'Cyberpunk man portrait 22' },
    ]
  },
  packType: 'cyberpunk'
} 