export const dreamlandKidsConfig = {
  title: "Dreamland Kids Portrait Collection",
  description: "Create magical and whimsical portraits for children in dreamlike settings that capture their imagination and joy",
  categories: [
    { name: 'All', value: 'all' },
    { name: 'Girls', value: 'girls' },
    { name: 'Boys', value: 'boys' }
  ],
  images: {
    girls: [
      { src: '/Packs/Dreamland Kids/Girls/girl1.jpg', alt: 'Magical dreamland girl portrait 1' },
      { src: '/Packs/Dreamland Kids/Girls/girl2.jpg', alt: 'Whimsical girl portrait 2' },
      { src: '/Packs/Dreamland Kids/Girls/girl3.jpg', alt: 'Dreamy girl portrait 3' },
      { src: '/Packs/Dreamland Kids/Girls/girl4.jpg', alt: 'Fantasy girl portrait 4' },
      { src: '/Packs/Dreamland Kids/Girls/girl5.jpg', alt: 'Magical girl portrait 5' },
      { src: '/Packs/Dreamland Kids/Girls/girl6.jpg', alt: 'Dreamland girl portrait 6' },
      { src: '/Packs/Dreamland Kids/Girls/girl7.jpg', alt: 'Fairy tale girl portrait 7' },
      { src: '/Packs/Dreamland Kids/Girls/girl8.jpg', alt: 'Enchanted girl portrait 8' },
      { src: '/Packs/Dreamland Kids/Girls/girl9.jpg', alt: 'Magical girl portrait 9' },
      { src: '/Packs/Dreamland Kids/Girls/girl10.jpg', alt: 'Dreamy girl portrait 10' },
      { src: '/Packs/Dreamland Kids/Girls/girl11.jpg', alt: 'Fantasy girl portrait 11' },
      { src: '/Packs/Dreamland Kids/Girls/girl12.jpg', alt: 'Magical girl portrait 12' },
      { src: '/Packs/Dreamland Kids/Girls/girl13.jpg', alt: 'Dreamland girl portrait 13' },
      { src: '/Packs/Dreamland Kids/Girls/girl14.jpg', alt: 'Adventure girl portrait 14' },
      { src: '/Packs/Dreamland Kids/Girls/girl15.jpg', alt: 'Enchanted girl portrait 15' },
      { src: '/Packs/Dreamland Kids/Girls/girl16.jpg', alt: 'Magical girl portrait 16' },
      { src: '/Packs/Dreamland Kids/Girls/girl17.jpg', alt: 'Dreamy girl portrait 17' },
      { src: '/Packs/Dreamland Kids/Girls/girl18.jpg', alt: 'Fantasy girl portrait 18' },
      { src: '/Packs/Dreamland Kids/Girls/girl19.jpg', alt: 'Magical girl portrait 19' },
      { src: '/Packs/Dreamland Kids/Girls/girl20.jpg', alt: 'Dreamland girl portrait 20' },
      { src: '/Packs/Dreamland Kids/Girls/girl21.jpg', alt: 'Adventure girl portrait 21' },
      { src: '/Packs/Dreamland Kids/Girls/girl22.jpg', alt: 'Enchanted girl portrait 22' },
      { src: '/Packs/Dreamland Kids/Girls/girl23.jpg', alt: 'Magical girl portrait 23' },
      { src: '/Packs/Dreamland Kids/Girls/girl24.jpg', alt: 'Dreamy girl portrait 24' },
    ],
    boys: [
      { src: '/Packs/Dreamland Kids/Boys/boy1.jpg', alt: 'Magical dreamland boy portrait 1' },
      { src: '/Packs/Dreamland Kids/Boys/boy2.jpg', alt: 'Whimsical boy portrait 2' },
      { src: '/Packs/Dreamland Kids/Boys/boy3.jpg', alt: 'Dreamy boy portrait 3' },
      { src: '/Packs/Dreamland Kids/Boys/boy4.jpg', alt: 'Fantasy boy portrait 4' },
      { src: '/Packs/Dreamland Kids/Boys/boy5.jpg', alt: 'Magical boy portrait 5' },
      { src: '/Packs/Dreamland Kids/Boys/boy6.jpg', alt: 'Dreamland boy portrait 6' },
      { src: '/Packs/Dreamland Kids/Boys/boy7.jpg', alt: 'Adventure boy portrait 7' },
      { src: '/Packs/Dreamland Kids/Boys/boy8.jpg', alt: 'Enchanted boy portrait 8' },
      { src: '/Packs/Dreamland Kids/Boys/boy9.jpg', alt: 'Magical boy portrait 9' },
      { src: '/Packs/Dreamland Kids/Boys/boy10.jpg', alt: 'Dreamy boy portrait 10' },
      { src: '/Packs/Dreamland Kids/Boys/boy11.jpg', alt: 'Fantasy boy portrait 11' },
      { src: '/Packs/Dreamland Kids/Boys/boy12.jpg', alt: 'Magical boy portrait 12' },
      { src: '/Packs/Dreamland Kids/Boys/boy13.jpg', alt: 'Dreamland boy portrait 13' },
      { src: '/Packs/Dreamland Kids/Boys/boy14.jpg', alt: 'Adventure boy portrait 14' },
      { src: '/Packs/Dreamland Kids/Boys/boy15.jpg', alt: 'Enchanted boy portrait 15' },
      { src: '/Packs/Dreamland Kids/Boys/boy16.jpg', alt: 'Magical boy portrait 16' },
      { src: '/Packs/Dreamland Kids/Boys/boy17.jpg', alt: 'Dreamy boy portrait 17' },
      { src: '/Packs/Dreamland Kids/Boys/boy18.jpg', alt: 'Fantasy boy portrait 18' },
      { src: '/Packs/Dreamland Kids/Boys/boy19.jpg', alt: 'Magical boy portrait 19' },
      { src: '/Packs/Dreamland Kids/Boys/boy20.jpg', alt: 'Dreamland boy portrait 20' },
      { src: '/Packs/Dreamland Kids/Boys/boy21.jpg', alt: 'Adventure boy portrait 21' },
      { src: '/Packs/Dreamland Kids/Boys/boy22.jpg', alt: 'Enchanted boy portrait 22' },
      { src: '/Packs/Dreamland Kids/Boys/boy23.jpg', alt: 'Magical boy portrait 23' },
      { src: '/Packs/Dreamland Kids/Boys/boy24.jpg', alt: 'Dreamy boy portrait 24' },
      { src: '/Packs/Dreamland Kids/Boys/boy25.jpg', alt: 'Fantasy boy portrait 25' },
      { src: '/Packs/Dreamland Kids/Boys/boy26.jpg', alt: 'Magical boy portrait 26' },
      { src: '/Packs/Dreamland Kids/Boys/boy27.jpg', alt: 'Dreamland boy portrait 27' },
      { src: '/Packs/Dreamland Kids/Boys/boy28.jpg', alt: 'Adventure boy portrait 28' },
      { src: '/Packs/Dreamland Kids/Boys/boy29.jpg', alt: 'Enchanted boy portrait 29' },
      { src: '/Packs/Dreamland Kids/Boys/boy30.jpg', alt: 'Magical boy portrait 30' },
    ]
  },
  packType: 'dreamland-kids'
} 