export const lawyerBrandedConfig = {
  title: "Lawyer Branded Portrait Collection",
  description: "Create professional legal portraits perfect for law firms and legal professionals",
  categories: [
    { name: 'All', value: 'all' },
    { name: 'Women', value: 'women' },
    { name: 'Men', value: 'men' }
  ],
  images: {
    women: [
      { src: '/Packs/Lawyer Branded/Women/women1.jpg', alt: 'Lawyer branded woman portrait 1' },
      { src: '/Packs/Lawyer Branded/Women/women2.jpg', alt: 'Lawyer branded woman portrait 2' },
      { src: '/Packs/Lawyer Branded/Women/women3.jpg', alt: 'Lawyer branded woman portrait 3' },
      { src: '/Packs/Lawyer Branded/Women/women4.jpg', alt: 'Lawyer branded woman portrait 4' },
      { src: '/Packs/Lawyer Branded/Women/women5.jpg', alt: 'Lawyer branded woman portrait 5' },
      { src: '/Packs/Lawyer Branded/Women/women6.jpg', alt: 'Lawyer branded woman portrait 6' },
      { src: '/Packs/Lawyer Branded/Women/women7.jpg', alt: 'Lawyer branded woman portrait 7' },
      { src: '/Packs/Lawyer Branded/Women/women8.jpg', alt: 'Lawyer branded woman portrait 8' },
      { src: '/Packs/Lawyer Branded/Women/women9.jpg', alt: 'Lawyer branded woman portrait 9' },
      { src: '/Packs/Lawyer Branded/Women/women10.jpg', alt: 'Lawyer branded woman portrait 10' },
      { src: '/Packs/Lawyer Branded/Women/women11.jpg', alt: 'Lawyer branded woman portrait 11' },
      { src: '/Packs/Lawyer Branded/Women/women12.jpg', alt: 'Lawyer branded woman portrait 12' },
      { src: '/Packs/Lawyer Branded/Women/women13.jpg', alt: 'Lawyer branded woman portrait 13' },
      { src: '/Packs/Lawyer Branded/Women/women14.jpg', alt: 'Lawyer branded woman portrait 14' },
      { src: '/Packs/Lawyer Branded/Women/women15.jpg', alt: 'Lawyer branded woman portrait 15' },
      { src: '/Packs/Lawyer Branded/Women/women16.jpg', alt: 'Lawyer branded woman portrait 16' },
      { src: '/Packs/Lawyer Branded/Women/women17.jpg', alt: 'Lawyer branded woman portrait 17' },
      { src: '/Packs/Lawyer Branded/Women/women18.jpg', alt: 'Lawyer branded woman portrait 18' },
      { src: '/Packs/Lawyer Branded/Women/women19.jpg', alt: 'Lawyer branded woman portrait 19' },
      { src: '/Packs/Lawyer Branded/Women/women20.jpg', alt: 'Lawyer branded woman portrait 20' },
    ],
    men: [
      { src: '/Packs/Lawyer Branded/Man/man1.jpg', alt: 'Lawyer branded man portrait 1' },
      { src: '/Packs/Lawyer Branded/Man/man2.jpg', alt: 'Lawyer branded man portrait 2' },
      { src: '/Packs/Lawyer Branded/Man/man3.jpg', alt: 'Lawyer branded man portrait 3' },
      { src: '/Packs/Lawyer Branded/Man/man4.jpg', alt: 'Lawyer branded man portrait 4' },
      { src: '/Packs/Lawyer Branded/Man/man5.jpg', alt: 'Lawyer branded man portrait 5' },
      { src: '/Packs/Lawyer Branded/Man/man6.jpg', alt: 'Lawyer branded man portrait 6' },
      { src: '/Packs/Lawyer Branded/Man/man7.jpg', alt: 'Lawyer branded man portrait 7' },
      { src: '/Packs/Lawyer Branded/Man/man8.jpg', alt: 'Lawyer branded man portrait 8' },
      { src: '/Packs/Lawyer Branded/Man/man9.jpg', alt: 'Lawyer branded man portrait 9' },
      { src: '/Packs/Lawyer Branded/Man/man10.jpg', alt: 'Lawyer branded man portrait 10' },
      { src: '/Packs/Lawyer Branded/Man/man11.jpg', alt: 'Lawyer branded man portrait 11' },
      { src: '/Packs/Lawyer Branded/Man/man12.jpg', alt: 'Lawyer branded man portrait 12' },
      { src: '/Packs/Lawyer Branded/Man/man13.jpg', alt: 'Lawyer branded man portrait 13' },
      { src: '/Packs/Lawyer Branded/Man/man14.jpg', alt: 'Lawyer branded man portrait 14' },
      { src: '/Packs/Lawyer Branded/Man/man15.jpg', alt: 'Lawyer branded man portrait 15' },
      { src: '/Packs/Lawyer Branded/Man/man16.jpg', alt: 'Lawyer branded man portrait 16' },
      { src: '/Packs/Lawyer Branded/Man/man17.jpg', alt: 'Lawyer branded man portrait 17' },
      { src: '/Packs/Lawyer Branded/Man/man18.jpg', alt: 'Lawyer branded man portrait 18' },
      { src: '/Packs/Lawyer Branded/Man/man19.jpg', alt: 'Lawyer branded man portrait 19' },
      { src: '/Packs/Lawyer Branded/Man/man20.jpg', alt: 'Lawyer branded man portrait 20' },
    ]
  },
  packType: 'lawyer-branded'
} 