export const stylishLawyersConfig = {
  title: "Stylish Lawyers Portrait Collection",
  description: "Create sophisticated and stylish portraits perfect for modern law professionals",
  categories: [
    { name: 'All', value: 'all' },
    { name: 'Women', value: 'women' },
    { name: 'Men', value: 'men' }
  ],
  images: {
    women: [
      { src: '/Packs/Stylish Look/Women/women1.jpg', alt: 'Stylish lawyer woman portrait 1' },
      { src: '/Packs/Stylish Look/Women/women2.jpg', alt: 'Stylish lawyer woman portrait 2' },
      { src: '/Packs/Stylish Look/Women/women3.jpg', alt: 'Stylish lawyer woman portrait 3' },
      { src: '/Packs/Stylish Look/Women/women4.jpg', alt: 'Stylish lawyer woman portrait 4' },
      { src: '/Packs/Stylish Look/Women/women5.jpg', alt: 'Stylish lawyer woman portrait 5' },
      { src: '/Packs/Stylish Look/Women/women6.jpg', alt: 'Stylish lawyer woman portrait 6' },
      { src: '/Packs/Stylish Look/Women/women7.jpg', alt: 'Stylish lawyer woman portrait 7' },
      { src: '/Packs/Stylish Look/Women/women8.jpg', alt: 'Stylish lawyer woman portrait 8' },
      { src: '/Packs/Stylish Look/Women/women9.jpg', alt: 'Stylish lawyer woman portrait 9' },
      { src: '/Packs/Stylish Look/Women/women10.jpg', alt: 'Stylish lawyer woman portrait 10' },
      { src: '/Packs/Stylish Look/Women/women11.jpg', alt: 'Stylish lawyer woman portrait 11' },
      { src: '/Packs/Stylish Look/Women/women12.jpg', alt: 'Stylish lawyer woman portrait 12' },
      { src: '/Packs/Stylish Look/Women/women13.jpg', alt: 'Stylish lawyer woman portrait 13' },
      { src: '/Packs/Stylish Look/Women/women14.jpg', alt: 'Stylish lawyer woman portrait 14' },
      { src: '/Packs/Stylish Look/Women/women15.jpg', alt: 'Stylish lawyer woman portrait 15' },
      { src: '/Packs/Stylish Look/Women/women16.jpg', alt: 'Stylish lawyer woman portrait 16' },
      { src: '/Packs/Stylish Look/Women/women17.jpg', alt: 'Stylish lawyer woman portrait 17' },
      { src: '/Packs/Stylish Look/Women/women18.jpg', alt: 'Stylish lawyer woman portrait 18' },
      { src: '/Packs/Stylish Look/Women/women19.jpg', alt: 'Stylish lawyer woman portrait 19' },
      { src: '/Packs/Stylish Look/Women/women20.jpg', alt: 'Stylish lawyer woman portrait 20' },
    ],
    men: [
      { src: '/Packs/Stylish Look/Man/man1.jpg', alt: 'Stylish lawyer man portrait 1' },
      { src: '/Packs/Stylish Look/Man/man2.jpg', alt: 'Stylish lawyer man portrait 2' },
      { src: '/Packs/Stylish Look/Man/man3.jpg', alt: 'Stylish lawyer man portrait 3' },
      { src: '/Packs/Stylish Look/Man/man4.jpg', alt: 'Stylish lawyer man portrait 4' },
      { src: '/Packs/Stylish Look/Man/man5.jpg', alt: 'Stylish lawyer man portrait 5' },
      { src: '/Packs/Stylish Look/Man/man6.jpg', alt: 'Stylish lawyer man portrait 6' },
      { src: '/Packs/Stylish Look/Man/man7.jpg', alt: 'Stylish lawyer man portrait 7' },
      { src: '/Packs/Stylish Look/Man/man8.jpg', alt: 'Stylish lawyer man portrait 8' },
      { src: '/Packs/Stylish Look/Man/man9.jpg', alt: 'Stylish lawyer man portrait 9' },
      { src: '/Packs/Stylish Look/Man/man10.jpg', alt: 'Stylish lawyer man portrait 10' },
      { src: '/Packs/Stylish Look/Man/man11.jpg', alt: 'Stylish lawyer man portrait 11' },
      { src: '/Packs/Stylish Look/Man/man12.jpg', alt: 'Stylish lawyer man portrait 12' },
      { src: '/Packs/Stylish Look/Man/man13.jpg', alt: 'Stylish lawyer man portrait 13' },
      { src: '/Packs/Stylish Look/Man/man14.jpg', alt: 'Stylish lawyer man portrait 14' },
      { src: '/Packs/Stylish Look/Man/man15.jpg', alt: 'Stylish lawyer man portrait 15' },
      { src: '/Packs/Stylish Look/Man/man16.jpg', alt: 'Stylish lawyer man portrait 16' },
      { src: '/Packs/Stylish Look/Man/man17.jpg', alt: 'Stylish lawyer man portrait 17' },
      { src: '/Packs/Stylish Look/Man/man18.jpg', alt: 'Stylish lawyer man portrait 18' },
      { src: '/Packs/Stylish Look/Man/man19.jpg', alt: 'Stylish lawyer man portrait 19' },
      { src: '/Packs/Stylish Look/Man/man20.jpg', alt: 'Stylish lawyer man portrait 20' },
    ]
  },
  packType: 'stylish-lawyers'
} 