import Link from 'next/link';
import Image from 'next/image';

// Add a props interface
interface WhyProps {
  imageSet?: 'dating' | 'doctor' | 'Jfram' | 'ColorFram' | 'GlmFram' | 'FitFram' | 'tubefram'  | 'Group6' | 'Group7' | 'Group8' | 'Group9' | 'Group10' |
   'Group11' | 'Group12' | 'Group13' | 'Group14' | 'Group15' | 'Group16' | 'Group17' | 'Group18' | 'Group19' | 'Group20' | 'Group21' | 'Group22';  // default will be 'dating'
}

const Why = ({ imageSet = 'dating' }: WhyProps) => {
  const features = [
    {
      icon: "/why/camera.png",
      title: "SIMPLIFIED PROCESS",
      description: "Skip the expensive photoshoot and the awkward\n poses.Get your professional headshots anytime, anywhere with just a few clear selfies or casual\n photos."
    },
    {
      icon: "/why/dollor.png",
      title: "VALUED MONEY",
      description: "All of this for the price of a lunch—what's there to lose?"
    },
    {
      icon: "/why/star.png",
      title: "VALUED TIME",
      description: "Instead of booking, posing, and waiting for edits,\nget your pictures in under an hour."
    },
    {
      icon: "/why/view.png",
      title: "QUALITY RESULTS",
      description: "Less time and more comfort doesn't mean compromising on quality."
    }
  ];

  const images = {
    dating: "/datingfram.png",
    doctor: "/doctorfram.png" , // Add your doctor frame image
    Jfram: "/Jfram.png",
    ColorFram: "/ColorFram.png",
    GlmFram: "/GlmFram.png",
    FitFram: "/FitFram.png",
    tubefram:"/tubefram.png",
    Group6:"/Group6.png",
    Group7:"/Group7.png",
    Group8:"/Group8.png",
    Group9:"/Group9.png",
    Group10:"/Group10.png",
    Group11:"/Group11.png",
    Group12:"/Group12.png",
    Group13:"/Group13.png",
    Group14:"/Group14.png",
    Group15:"/Group15.png",
    Group16:"/Group16.png",
    Group17:"/Group17.png",
    Group18:"/Group18.png",
    Group19:"/Group19.png",
    Group20:"/Group20.png",
    Group21:"/Group21.png",
    Group22:"/Group22.png",
  };

  return (
    <section className="bg-white py-10 sm:py-16 lg:py-20 rounded-[60px]">
      <div className="max-w-[1276px] mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-12 lg:mb-16">
          <h1 className="text-[28px] sm:text-[32px] lg:text-[40px] font-bold mb-4">Why GoStudio.ai?</h1>
          <p className="text-gray-600 max-w-[800px] mx-auto text-sm sm:text-base">
            {imageSet === 'doctor' ? 
              "Professional headshots generated by GoStudio.ai highlight expertise, trustworthiness, and approachability, ensuring you make a strong impression in the medical field." :
              "Dating headshots generated by GoStudio.ai highlight authenticity, warmth, and charm, ensuring you make a genuine connection by showcasing the best version of yourself."
            }
          </p>
        </div>

        <div className="flex flex-col lg:flex-row justify-between gap-8 lg:gap-0">
          {/* Features Section */}
          <div className="w-full lg:w-[517px] space-y-6 sm:space-y-8">
            {features.map((feature, index) => (
              <div key={index} className="flex items-start gap-4 sm:gap-6">
                <div className="w-[40px] h-[40px] sm:w-[51px] sm:h-[51px] flex-shrink-0 flex items-center justify-center">
                  <Image 
                    src={feature.icon}
                    alt={feature.title}
                    width={51}
                    height={51}
                    className="object-contain w-full h-full"
                  />
                </div>
                <div>
                  <h3 className="text-base sm:text-lg lg:text-xl font-bold mb-2">{feature.title}</h3>
                  <p className="text-gray-600 text-sm sm:text-base whitespace-pre-line">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Updated Images Section */}
          <div className="relative w-full lg:w-[556px] h-[555px] mt-8 lg:mt-0">
            <div className="relative w-full h-full">
              <Image
                src={images[imageSet]}
                alt={`${imageSet} AI Headshot Examples`}
                fill
                className="object-contain"
                style={{
                  filter: 'drop-shadow(0px 4px 20px rgba(0, 0, 0, 0.1))',
                  borderRadius: '24px',
                }}
              />
            </div>
          </div>
        </div>

        <div className="text-center mt-8 sm:mt-12 lg:mt-16">
          <Link 
            href="/get-started" 
            className="inline-block bg-[#5B16FE] text-white px-6 sm:px-8 py-3 sm:py-4 rounded-full text-base sm:text-lg hover:bg-opacity-90 transition-all"
          >
            Get Your Headshot now →
          </Link>
        </div>
      </div>
    </section>
  );
};

export default Why;