import Link from 'next/link';
import Image from 'next/image';

const Why = () => {
  const features = [
    {
      icon: "/why/camera.png",
      title: "SIMPLIFIED PROCESS",
      description: "Skip the expensive photoshoot and the awkward poses. Get your professional headshots anytime, anywhere with just a few clear selfies or casual photos."
    },
    {
      icon: "/why/dollor.png",
      title: "VALUED MONEY",
      description: "All of this for the price of a lunch—what's there to lose?"
    },
    {
      icon: "/why/star.png",
      title: "VALUED TIME",
      description: "Instead of booking, posing, and waiting for edits, get your pictures in under an hour and spend your time doing what you love."
    },
    {
      icon: "/why/view.png",
      title: "QUALITY RESULTS",
      description: "Less time and more comfort doesn't mean compromising on quality."
    }
  ];

  return (
    <section className="bg-white py-10 sm:py-16 lg:py-20 rounded-[60px]">
      <div className="max-w-[1276px] mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-12 lg:mb-16">
          <h1 className="text-[28px] sm:text-[32px] lg:text-[40px] font-bold mb-4">Why GoStudio.ai?</h1>
          <p className="text-gray-600 max-w-[800px] mx-auto text-sm sm:text-base">
            Dating headshots generated by GoStudio.ai highlight authenticity, warmth, and charm, 
            ensuring you make a genuine connection by showcasing the best version of yourself.
          </p>
        </div>

        <div className="flex flex-col lg:flex-row justify-between gap-8 lg:gap-0">
          {/* Features Section */}
          <div className="w-full lg:w-[418px] space-y-6 sm:space-y-8 lg:pl-[50px]">
            {features.map((feature, index) => (
              <div key={index} className="flex items-start gap-4 sm:gap-6">
                <div className="w-[40px] h-[40px] sm:w-[51px] sm:h-[51px] flex-shrink-0 flex items-center justify-center">
                  <Image 
                    src={feature.icon}
                    alt={feature.title}
                    width={51}
                    height={51}
                    className="object-contain w-full h-full"
                  />
                </div>
                <div>
                  <h3 className="text-base sm:text-lg lg:text-xl font-bold mb-2">{feature.title}</h3>
                  <p className="text-gray-600 text-sm sm:text-base">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Images Section */}
          <div className="relative w-full lg:w-[600px] h-[400px] sm:h-[500px] lg:h-[600px] mt-8 lg:mt-0">
            <div className="absolute hidden sm:block" style={{ top: '33.61px', left: '39px', transform: 'rotate(6.79deg)' }}>
              <Image
                src="/why/men.png"
                alt="Men headshot"
                width={170}
                height={170}
                className="rounded-[12px] shadow-lg"
              />
            </div>
            <div className="absolute" style={{ top: '60.61px', left: '283px', transform: 'rotate(-6.86deg)' }}>
              <Image
                src="/why/girl.png"
                alt="Women headshot"
                width={232}
                height={232}
                className="rounded-[12px] shadow-lg"
              />
            </div>
            <div className="absolute" style={{ top: '288.61px', left: '0', transform: 'rotate(12.46deg)' }}>
              <Image
                src="/why/women.png"
                alt="Girl headshot"
                width={260}
                height={260}
                className="rounded-[12px] border-[2.24px] border-white shadow-lg"
              />
            </div>
          </div>
        </div>

        <div className="text-center mt-8 sm:mt-12 lg:mt-16">
          <Link 
            href="/get-started" 
            className="inline-block bg-[#5B16FE] text-white px-6 sm:px-8 py-3 sm:py-4 rounded-full text-base sm:text-lg hover:bg-opacity-90 transition-all"
          >
            Get Your Headshot now →
          </Link>
        </div>
      </div>
    </section>
  );
};

export default Why;