// Define the interface for type safety
interface PackImagePaths {
  [key: string]: string[];
}

// Export a single packImages constant
export const packImages: PackImagePaths = {
  'doctor': [
    '/Packs/Doctor-photos/Man/man1.jpg',
    '/Packs/Doctor-photos/Man/man2.jpg',
    '/Packs/Doctor-photos/Man/man3.jpg',
    '/Packs/Doctor-photos/Man/man4.jpg',
    '/Packs/Doctor-photos/Man/man5.jpg',
    '/Packs/Doctor-photos/Women/women1.jpg',
    '/Packs/Doctor-photos/Women/women2.jpg',
    '/Packs/Doctor-photos/Women/women3.jpg',
    '/Packs/Doctor-photos/Women/women4.jpg',
    '/Packs/Doctor-photos/Women/women5.jpg',
  ],
  'redcarpet': [
    '/Packs/Redcarpat-photos/Man/man1.jpg',
    '/Packs/Redcarpat-photos/Man/man2.jpg',
    '/Packs/Redcarpat-photos/Man/man3.jpg',
    '/Packs/Redcarpat-photos/Man/man4.jpg',
    '/Packs/Redcarpat-photos/Man/man5.jpg',
    '/Packs/Redcarpat-photos/Women/women1.jpg',
    '/Packs/Redcarpat-photos/Women/women2.jpg',
    '/Packs/Redcarpat-photos/Women/women3.jpg',
    '/Packs/Redcarpat-photos/Women/women4.jpg',
    '/Packs/Redcarpat-photos/Women/women5.jpg',
  ],
  'americana': [
    '/Packs/Americana-photos/Man/man1.jpg',
    '/Packs/Americana-photos/Man/man2.jpg',
    '/Packs/Americana-photos/Man/man3.jpg',
    '/Packs/Americana-photos/Man/man4.jpg',
    '/Packs/Americana-photos/Man/man5.jpg',
    '/Packs/Americana-photos/Women/women1.jpg',
    '/Packs/Americana-photos/Women/women2.jpg',
    '/Packs/Americana-photos/Women/women3.jpg',
    '/Packs/Americana-photos/Women/women4.jpg',
    '/Packs/Americana-photos/Women/women5.jpg',
  ],
  'corporate': [
    '/Packs/Speaker-photos/Man/man1.jpg',
    '/Packs/Speaker-photos/Man/man2.jpg',
    '/Packs/Speaker-photos/Man/man3.jpg',
    '/Packs/Speaker-photos/Man/man4.jpg',
    '/Packs/Speaker-photos/Man/man5.jpg',
    '/Packs/Speaker-photos/Women/women1.jpg',
    '/Packs/Speaker-photos/Women/women2.jpg',
    '/Packs/Speaker-photos/Women/women3.jpg',
    '/Packs/Speaker-photos/Women/women4.jpg',
    '/Packs/Speaker-photos/Women/women5.jpg',
  ],
  'artistic': [
    '/Packs/Artistic-photos/Man/man1.jpg',
    '/Packs/Artistic-photos/Man/man2.jpg',
    '/Packs/Artistic-photos/Man/man3.jpg',
    '/Packs/Artistic-photos/Man/man4.jpg',
    '/Packs/Artistic-photos/Man/man5.jpg',
    '/Packs/Artistic-photos/Women/women1.jpg',
    '/Packs/Artistic-photos/Women/women2.jpg',
    '/Packs/Artistic-photos/Women/women3.jpg',
    '/Packs/Artistic-photos/Women/women4.jpg',
    '/Packs/Artistic-photos/Women/women5.jpg',
  ],
  'speaker': [
    '/Packs/Speaker-photos/Man/man1.jpg',
    '/Packs/Speaker-photos/Man/man2.jpg',
    '/Packs/Speaker-photos/Man/man3.jpg',
    '/Packs/Speaker-photos/Man/man4.jpg',
    '/Packs/Speaker-photos/Man/man5.jpg',
    '/Packs/Speaker-photos/Women/women1.jpg',
    '/Packs/Speaker-photos/Women/women2.jpg',
    '/Packs/Speaker-photos/Women/women3.jpg',
    '/Packs/Speaker-photos/Women/women4.jpg',
    '/Packs/Speaker-photos/Women/women5.jpg',
  ],
  'realtor': [
    '/Packs/Realtor-photos/Man/man1.jpg',
    '/Packs/Realtor-photos/Man/man2.jpg',
    '/Packs/Realtor-photos/Man/man3.jpg',
    '/Packs/Realtor-photos/Man/man4.jpg',
    '/Packs/Realtor-photos/Man/man5.jpg',
    '/Packs/Realtor-photos/Women/women1.jpg',
    '/Packs/Realtor-photos/Women/women2.jpg',
    '/Packs/Realtor-photos/Women/women3.jpg',
    '/Packs/Realtor-photos/Women/women4.jpg',
    '/Packs/Realtor-photos/Women/women5.jpg',
  ],
  'dating': [
    '/Packs/Dating-photo/Man/man1.jpg',
    '/Packs/Dating-photo/Man/man2.jpg',
    '/Packs/Dating-photo/Man/man3.jpg',
    '/Packs/Dating-photo/Man/man4.jpg',
    '/Packs/Dating-photo/Man/man5.jpg',
    '/Packs/Dating-photo/Women/women1.jpg',
    '/Packs/Dating-photo/Women/women2.jpg',
    '/Packs/Dating-photo/Women/women3.jpg',
    '/Packs/Dating-photo/Women/women4.jpg',
    '/Packs/Dating-photo/Women/women5.jpg',
  ],
  'boldcolors': [
    '/Packs/Boldcolors-photos/Man/man1.jpg',
    '/Packs/Boldcolors-photos/Man/man2.jpg',
    '/Packs/Boldcolors-photos/Man/man3.jpg',
    '/Packs/Boldcolors-photos/Man/man4.jpg',
    '/Packs/Boldcolors-photos/Man/man5.jpg',
    '/Packs/Boldcolors-photos/Women/women1.jpg',
    '/Packs/Boldcolors-photos/Women/women2.jpg',
    '/Packs/Boldcolors-photos/Women/women3.jpg',
    '/Packs/Boldcolors-photos/Women/women4.jpg',
    '/Packs/Boldcolors-photos/Women/women5.jpg',
  ],
  'tattoos': [
    '/Packs/Tattos-photos/Man/man1.jpg',
    '/Packs/Tattos-photos/Man/man2.jpg',
    '/Packs/Tattos-photos/Man/man3.jpg',
    '/Packs/Tattos-photos/Man/man4.jpg',
    '/Packs/Tattos-photos/Man/man5.jpg',
    '/Packs/Tattos-photos/Women/women1.jpg',
    '/Packs/Tattos-photos/Women/women2.jpg',
    '/Packs/Tattos-photos/Women/women3.jpg',
    '/Packs/Tattos-photos/Women/women4.jpg',
    '/Packs/Tattos-photos/Women/women5.jpg',
  ],
  'glamour': [
    '/Packs/Glamour-photos/Man/man1.jpg',
    '/Packs/Glamour-photos/Man/man2.jpg',
    '/Packs/Glamour-photos/Man/man3.jpg',
    '/Packs/Glamour-photos/Man/man4.jpg',
    '/Packs/Glamour-photos/Man/man5.jpg',
    '/Packs/Glamour-photos/Women/women1.jpg',
    '/Packs/Glamour-photos/Women/women2.jpg',
    '/Packs/Glamour-photos/Women/women3.jpg',
    '/Packs/Glamour-photos/Women/women4.jpg',
    '/Packs/Glamour-photos/Women/women5.jpg',
  ],
  'barbie': [
    
    '/Packs/Barbie-photos/Women/women1.jpg',
    '/Packs/Barbie-photos/Women/women2.jpg',
    '/Packs/Barbie-photos/Women/women3.jpg',
    '/Packs/Barbie-photos/Women/women4.jpg',
    '/Packs/Barbie-photos/Women/women5.jpg',
  ],
  'halloween': [
    '/Packs/Halloween-photos/Man/man1.jpg',
    '/Packs/Halloween-photos/Man/man2.jpg',
    '/Packs/Halloween-photos/Man/man3.jpg',
    '/Packs/Halloween-photos/Man/man4.jpg',
    '/Packs/Halloween-photos/Man/man5.jpg',
    '/Packs/Halloween-photos/Women/women1.jpg',
    '/Packs/Halloween-photos/Women/women2.jpg',
    '/Packs/Halloween-photos/Women/women3.jpg',
    '/Packs/Halloween-photos/Women/women4.jpg',
    '/Packs/Halloween-photos/Women/women5.jpg',
  ],
  'mythicalcreatures': [
    '/Packs/Mythical-photos/Man/man1.jpg',
    '/Packs/Mythical-photos/Man/man2.jpg',
    '/Packs/Mythical-photos/Man/man3.jpg',
    '/Packs/Mythical-photos/Man/man4.jpg',
    '/Packs/Mythical-photos/Man/man5.jpg',
    '/Packs/Mythical-photos/Women/women1.jpg',
    '/Packs/Mythical-photos/Women/women2.jpg',
    '/Packs/Mythical-photos/Women/women3.jpg',
    '/Packs/Mythical-photos/Women/women4.jpg',
    '/Packs/Mythical-photos/Women/women5.jpg',
  ],
  'annie': [
    '/Packs/Annie-photos/Man/man1.jpg',
    '/Packs/Annie-photos/Man/man2.jpg',
    '/Packs/Annie-photos/Man/man3.jpg',
    '/Packs/Annie-photos/Women/women1.jpg',
    '/Packs/Annie-photos/Women/women2.jpg',
    '/Packs/Annie-photos/Women/women3.jpg',
    '/Packs/Annie-photos/Women/women4.jpg',
    '/Packs/Annie-photos/Women/women5.jpg',
  ],
  'dog': [
    '/Packs/Dog/dog1.jpg',
    '/Packs/Dog/dog2.jpg',
    '/Packs/Dog/dog3.jpg',
    '/Packs/Dog/dog4.jpg',
    '/Packs/Dog/dog5.jpg',
    '/Packs/Dog/dog6.jpg',
    '/Packs/Dog/dog7.jpg',
    '/Packs/Dog/dog8.jpg',
    
  ],
  'fitness': [
    '/Packs/Fitness-photos/Man/man1.jpg',
    '/Packs/Fitness-photos/Man/man2.jpg',
    '/Packs/Fitness-photos/Man/man3.jpg',
    '/Packs/Fitness-photos/Man/man4.jpg',
    '/Packs/Fitness-photos/Man/man5.jpg',
    '/Packs/Fitness-photos/Women/women1.jpg',
    '/Packs/Fitness-photos/Women/women2.jpg',
    '/Packs/Fitness-photos/Women/women3.jpg',
    '/Packs/Fitness-photos/Women/women4.jpg',
    '/Packs/Fitness-photos/Women/women5.jpg',
  ],
  'gamesofthrones': [
    '/Packs/Gamesofthrones-photos/Man/man1.jpg',
    '/Packs/Gamesofthrones-photos/Man/man2.jpg',
    '/Packs/Gamesofthrones-photos/Man/man3.jpg',
    '/Packs/Gamesofthrones-photos/Man/man4.jpg',
    '/Packs/Gamesofthrones-photos/Man/man5.jpg',
    '/Packs/Gamesofthrones-photos/Women/women1.jpg',
    '/Packs/Gamesofthrones-photos/Women/women2.jpg',
    '/Packs/Gamesofthrones-photos/Women/women3.jpg',
    '/Packs/Gamesofthrones-photos/Women/women4.jpg',
    '/Packs/Gamesofthrones-photos/Women/women5.jpg',
  ],
  'botanical': [
    '/Packs/Botnical-photos/Man/man1.jpg',
    '/Packs/Botnical-photos/Man/man2.jpg',
    '/Packs/Botnical-photos/Man/man3.jpg',
    '/Packs/Botnical-photos/Man/man4.jpg',
    '/Packs/Botnical-photos/Man/man5.jpg',
    '/Packs/Botnical-photos/Women/women1.jpg',
    '/Packs/Botnical-photos/Women/women2.jpg',
    '/Packs/Botnical-photos/Women/women3.jpg',
    '/Packs/Botnical-photos/Women/women4.jpg',
    '/Packs/Botnical-photos/Women/women5.jpg',
  ],
  'helmut': [
    '/Packs/Helmut-photos/Man/man1.jpg',
    '/Packs/Helmut-photos/Man/man2.jpg',
    '/Packs/Helmut-photos/Man/man3.jpg',
    '/Packs/Helmut-photos/Man/man4.jpg',
    '/Packs/Helmut-photos/Man/man5.jpg',
    '/Packs/Helmut-photos/Women/women1.jpg',
    '/Packs/Helmut-photos/Women/women2.jpg',
    '/Packs/Helmut-photos/Women/women3.jpg',
    '/Packs/Helmut-photos/Women/women4.jpg',
    '/Packs/Helmut-photos/Women/women5.jpg',
  ],
  'jcrew': [
    '/Packs/Jcrew-photos/Man/man1.jpg',
    '/Packs/Jcrew-photos/Man/man2.jpg',
    '/Packs/Jcrew-photos/Man/man3.jpg',
    '/Packs/Jcrew-photos/Man/man4.jpg',
    '/Packs/Jcrew-photos/Man/man5.jpg',
    '/Packs/Jcrew-photos/Women/women1.jpg',
    '/Packs/Jcrew-photos/Women/women2.jpg',
    '/Packs/Jcrew-photos/Women/women3.jpg',
    '/Packs/Jcrew-photos/Women/women4.jpg',
    '/Packs/Jcrew-photos/Women/women5.jpg',
  ],
  'birthday': [
    '/Packs/Kidsbirthday-photos/Boys/boy1.jpg',
    '/Packs/Kidsbirthday-photos/Boys/boy2.jpg',
    '/Packs/Kidsbirthday-photos/Boys/boy3.jpg',
    '/Packs/Kidsbirthday-photos/Boys/boy4.jpg',
    '/Packs/Kidsbirthday-photos/Boys/boy5.jpg',
    '/Packs/Kidsbirthday-photos/Girls/girls1.jpg',
    '/Packs/Kidsbirthday-photos/Girls/girls2.jpg',
    '/Packs/Kidsbirthday-photos/Girls/girls3.jpg',
    '/Packs/Kidsbirthday-photos/Girls/girls4.jpg',
    '/Packs/Kidsbirthday-photos/Girls/girls5.jpg',
  ],
  'vikings': [
    '/Packs/Vikings-photos/Man/man1.jpg',
    '/Packs/Vikings-photos/Man/man2.jpg',
    '/Packs/Vikings-photos/Man/man3.jpg',
    '/Packs/Vikings-photos/Man/man4.jpg',
    '/Packs/Vikings-photos/Man/man5.jpg',
    '/Packs/Vikings-photos/Women/women1.jpg',
    '/Packs/Vikings-photos/Women/women2.jpg',
    '/Packs/Vikings-photos/Women/women3.jpg',
    '/Packs/Vikings-photos/Women/women4.jpg',
    '/Packs/Vikings-photos/Women/women5.jpg',
  ],
  'wrestlemania': [
    '/Packs/Wreslemania-photos/Man/man1.jpg',
    '/Packs/Wreslemania-photos/Man/man2.jpg',
    '/Packs/Wreslemania-photos/Man/man3.jpg',
    '/Packs/Wreslemania-photos/Man/man4.jpg',
    '/Packs/Wreslemania-photos/Man/man5.jpg',
    '/Packs/Wreslemania-photos/Women/women1.jpg',
    '/Packs/Wreslemania-photos/Women/women2.jpg',
    '/Packs/Wreslemania-photos/Women/women3.jpg',
    '/Packs/Wreslemania-photos/Women/women4.jpg',
    '/Packs/Wreslemania-photos/Women/women5.jpg',
  ],
  'youtube': [
    '/Packs/Youtube-photos/Man/man1.jpg',
    '/Packs/Youtube-photos/Man/man.jpg',
    '/Packs/Youtube-photos/Women/women1.jpg',
    '/Packs/Youtube-photos/Women/women2.jpg',
    '/Packs/Youtube-photos/Women/women3.jpg',
    '/Packs/Youtube-photos/Women/women4.jpg',
    '/Packs/Youtube-photos/Women/women5.jpg',
  ],
  'onesie': [
    '/Packs/Onesise-phots/Man/man1.jpg',
    '/Packs/Onesise-phots/Man/man2.jpg',
    '/Packs/Onesise-phots/Man/man3.jpg',
    '/Packs/Onesise-phots/Man/man4.jpg',
    '/Packs/Onesise-phots/Man/man5.jpg',
    '/Packs/Onesise-phots/Women/women1.jpg',
    '/Packs/Onesise-phots/Women/women2.jpg',
    '/Packs/Onesise-phots/Women/women3.jpg',
    '/Packs/Onesise-phots/Women/women4.jpg',
    '/Packs/Onesise-phots/Women/women5.jpg',
  ],
  'hbdsave': [
    '/Packs/HBD-Date-Save/boys/man1.jpg',
    '/Packs/HBD-Date-Save/boys/man2.jpg',
    '/Packs/HBD-Date-Save/boys/man3.jpg',
    '/Packs/HBD-Date-Save/boys/man4.jpg',
    '/Packs/HBD-Date-Save/boys/man5.jpg',
    '/Packs/HBD-Date-Save/Girls/women1.jpg',
    '/Packs/HBD-Date-Save/Girls/women2.jpg',
    '/Packs/HBD-Date-Save/Girls/women3.jpg',
    '/Packs/HBD-Date-Save/Girls/women4.jpg',
    '/Packs/HBD-Date-Save/Girls/women5.jpg',
  ],
  'christmas': [
    '/Packs/Christmas Sweater/Man/man1.jpg',
    '/Packs/Christmas Sweater/Man/man2.jpg',
    '/Packs/Christmas Sweater/Man/man3.jpg',
    
    '/Packs/Christmas Sweater/Women/women1.jpg',
    '/Packs/Christmas Sweater/Women/women2.jpg',
    '/Packs/Christmas Sweater/Women/women3.jpg',
   
  ],
  'cat': [
    '/Packs/Cat Meowgic/cat1.jpg',
    '/Packs/Cat Meowgic/cat2.jpg',
    '/Packs/Cat Meowgic/cat3.jpg',
    '/Packs/Cat Meowgic/cat4.jpg',
    '/Packs/Cat Meowgic/cat5.jpg',
    '/Packs/Cat Meowgic/cat6.jpg',
    '/Packs/Cat Meowgic/cat7.jpg',
    '/Packs/Cat Meowgic/cat8.jpg',
  ],
  'iconic': [
    '/Packs/Me Iconic/Women/women1.jpg',
    '/Packs/Me Iconic/Women/women2.jpg',
    '/Packs/Me Iconic/Women/women3.jpg',
    '/Packs/Me Iconic/Women/women4.jpg',
    '/Packs/Me Iconic/Women/women5.jpg',
    '/Packs/Me Iconic/Women/women6.jpg',
    '/Packs/Me Iconic/Women/women7.jpg',
    '/Packs/Me Iconic/Women/women8.jpg',
    '/Packs/Me Iconic/Women/women9.jpg',
  ],
  'partner': [
    '/Packs/Partner headshots/Man/man1.jpg',
    '/Packs/Partner headshots/Man/man2.jpg',
    '/Packs/Partner headshots/Man/man3.jpg',
    '/Packs/Partner headshots/Man/man4.jpg',
    '/Packs/Partner headshots/Man/man5.jpg',
    '/Packs/Partner headshots/Women/women1.jpg',
    '/Packs/Partner headshots/Women/women2.jpg',
    '/Packs/Partner headshots/Women/women3.jpg',
    '/Packs/Partner headshots/Women/women4.jpg',
    '/Packs/Partner headshots/Women/women5.jpg',
  ],
  'wildfriends': [
    '/Packs/Wild Friends Forever/Man/man1.jpg',
    '/Packs/Wild Friends Forever/Man/man2.jpg',
    '/Packs/Wild Friends Forever/Man/man3.jpg',
    '/Packs/Wild Friends Forever/Man/man4.jpg',
    '/Packs/Wild Friends Forever/Man/man5.jpg',
    '/Packs/Wild Friends Forever/Women/women1.jpg',
    '/Packs/Wild Friends Forever/Women/women2.jpg',
    '/Packs/Wild Friends Forever/Women/women3.jpg',
    '/Packs/Wild Friends Forever/Women/women4.jpg',
    '/Packs/Wild Friends Forever/Women/women5.jpg',
  ],
  'winter': [
    '/Packs/Winter Wonderland/Man/man1.jpg',
    '/Packs/Winter Wonderland/Man/man2.jpg',
    '/Packs/Winter Wonderland/Man/man3.jpg',
    '/Packs/Winter Wonderland/Man/man4.jpg',
    '/Packs/Winter Wonderland/Man/man5.jpg',
    '/Packs/Winter Wonderland/Women/women1.jpg',
    '/Packs/Winter Wonderland/Women/women2.jpg',
    '/Packs/Winter Wonderland/Women/women3.jpg',
    '/Packs/Winter Wonderland/Women/women4.jpg',
    '/Packs/Winter Wonderland/Women/women5.jpg',
  ],
  'success': [
    '/Packs/Styled for Success/Man/man1.jpg',
    '/Packs/Styled for Success/Man/man2.jpg',
    '/Packs/Styled for Success/Man/man3.jpg',
    '/Packs/Styled for Success/Man/man4.jpg',
    '/Packs/Styled for Success/Man/man5.jpg',
    '/Packs/Styled for Success/Women/women1.jpg',
    '/Packs/Styled for Success/Women/women2.jpg',
    '/Packs/Styled for Success/Women/women3.jpg',
    '/Packs/Styled for Success/Women/women4.jpg',
    '/Packs/Styled for Success/Women/women5.jpg',
  ],
  'stylish': [
    '/Packs/Stylish Pro Portraits/Man/man1.jpg',
    '/Packs/Stylish Pro Portraits/Man/man2.jpg',
    '/Packs/Stylish Pro Portraits/Man/man3.jpg',
    '/Packs/Stylish Pro Portraits/Man/man4.jpg',
    '/Packs/Stylish Pro Portraits/Man/man5.jpg',
    '/Packs/Stylish Pro Portraits/Women/women1.jpg',
    '/Packs/Stylish Pro Portraits/Women/women2.jpg',
    '/Packs/Stylish Pro Portraits/Women/women3.jpg',
    '/Packs/Stylish Pro Portraits/Women/women4.jpg',
    '/Packs/Stylish Pro Portraits/Women/women5.jpg',
  ],
  'photoshoot': [
   
    
    '/reviews-all/photoshoot-woman7.jpg',
    '/reviews-all/photoshoot-woman8.jpg',
    '/reviews-all/photoshoot-woman9.jpg',
    '/reviews-all/photoshoot-woman6.jpg',
    '/reviews-all/photoshoot-woman5.jpg',
    '/reviews-all/photoshoot-man.jpg',
    '/reviews-all/photoshoot-women.jpg',
    
    
    '/reviews-all/photoshoot-women-nearlake.jpg',
    
 
  ],
}; 
