type PackImagePaths = {
  [key: string]: string[];
};

export const packImages: PackImagePaths = {
  'doctor': [
    '/Packs/Doctor-photos/Man/man1.jpg',
    '/Packs/Doctor-photos/Man/man2.jpg',
    '/Packs/Doctor-photos/Man/man3.jpg',
    '/Packs/Doctor-photos/Man/man4.jpg',
    '/Packs/Doctor-photos/Man/man5.jpg',
    '/Packs/Doctor-photos/Women/women1.jpg',
    '/Packs/Doctor-photos/Women/women2.jpg',
    '/Packs/Doctor-photos/Women/women3.jpg',
    '/Packs/Doctor-photos/Women/women4.jpg',
    '/Packs/Doctor-photos/Women/women5.jpg',
  ],
  'redcarpet': [
    '/Packs/Redcarpat-photos/Man/man1.jpg',
    '/Packs/Redcarpat-photos/Man/man2.jpg',
    '/Packs/Redcarpat-photos/Man/man3.jpg',
    '/Packs/Redcarpat-photos/Man/man4.jpg',
    '/Packs/Redcarpat-photos/Man/man5.jpg',
    '/Packs/Redcarpat-photos/Women/women1.jpg',
    '/Packs/Redcarpat-photos/Women/women2.jpg',
    '/Packs/Redcarpat-photos/Women/women3.jpg',
    '/Packs/Redcarpat-photos/Women/women4.jpg',
    '/Packs/Redcarpat-photos/Women/women5.jpg',
  ],
  'corporate': [
    '/Packs/Speaker-photos/Man/man1.jpg',
    '/Packs/Speaker-photos/Man/man2.jpg',
    '/Packs/Speaker-photos/Man/man3.jpg',
    '/Packs/Speaker-photos/Man/man4.jpg',
    '/Packs/Speaker-photos/Man/man5.jpg',
    '/Packs/Speaker-photos/Women/women1.jpg',
    '/Packs/Speaker-photos/Women/women2.jpg',
    '/Packs/Speaker-photos/Women/women3.jpg',
    '/Packs/Speaker-photos/Women/women4.jpg',
    '/Packs/Speaker-photos/Women/women5.jpg',
  ],
  'speaker': [
    '/Packs/Speaker-photos/Man/man1.jpg',
    '/Packs/Speaker-photos/Man/man2.jpg',
    '/Packs/Speaker-photos/Man/man3.jpg',
    '/Packs/Speaker-photos/Man/man4.jpg',
    '/Packs/Speaker-photos/Man/man5.jpg',
    '/Packs/Speaker-photos/Women/women1.jpg',
    '/Packs/Speaker-photos/Women/women2.jpg',
    '/Packs/Speaker-photos/Women/women3.jpg',
    '/Packs/Speaker-photos/Women/women4.jpg',
    '/Packs/Speaker-photos/Women/women5.jpg',
  ],
  'realtor': [
    '/Packs/Realtor-photos/Man/man1.jpg',
    '/Packs/Realtor-photos/Man/man2.jpg',
    '/Packs/Realtor-photos/Man/man3.jpg',
    '/Packs/Realtor-photos/Man/man4.jpg',
    '/Packs/Realtor-photos/Man/man5.jpg',
    '/Packs/Realtor-photos/Women/women1.jpg',
    '/Packs/Realtor-photos/Women/women2.jpg',
    '/Packs/Realtor-photos/Women/women3.jpg',
    '/Packs/Realtor-photos/Women/women4.jpg',
    '/Packs/Realtor-photos/Women/women5.jpg',
  ],
  'dating': [
    '/Packs/Dating-photo/Man/man1.jpg',
    '/Packs/Dating-photo/Man/man2.jpg',
    '/Packs/Dating-photo/Man/man3.jpg',
    '/Packs/Dating-photo/Man/man4.jpg',
    '/Packs/Dating-photo/Man/man5.jpg',
    '/Packs/Dating-photo/Women/women1.jpg',
    '/Packs/Dating-photo/Women/women2.jpg',
    '/Packs/Dating-photo/Women/women3.jpg',
    '/Packs/Dating-photo/Women/women4.jpg',
    '/Packs/Dating-photo/Women/women5.jpg',
  ],
  'boldcolors': [
    '/Packs/Boldcolors-photos/Man/man1.jpg',
    '/Packs/Boldcolors-photos/Man/man2.jpg',
    '/Packs/Boldcolors-photos/Man/man3.jpg',
    '/Packs/Boldcolors-photos/Man/man4.jpg',
    '/Packs/Boldcolors-photos/Man/man5.jpg',
    '/Packs/Boldcolors-photos/Women/women1.jpg',
    '/Packs/Boldcolors-photos/Women/women2.jpg',
    '/Packs/Boldcolors-photos/Women/women3.jpg',
    '/Packs/Boldcolors-photos/Women/women4.jpg',
    '/Packs/Boldcolors-photos/Women/women5.jpg',
  ],
  'tattoo': [
    '/Packs/Tattoo-photos/Man/man1.jpg',
    '/Packs/Tattoo-photos/Man/man2.jpg',
    '/Packs/Tattoo-photos/Man/man3.jpg',
    '/Packs/Tattoo-photos/Man/man4.jpg',
    '/Packs/Tattoo-photos/Man/man5.jpg',
    '/Packs/Tattoo-photos/Women/women1.jpg',
    '/Packs/Tattoo-photos/Women/women2.jpg',
    '/Packs/Tattoo-photos/Women/women3.jpg',
    '/Packs/Tattoo-photos/Women/women4.jpg',
    '/Packs/Tattoo-photos/Women/women5.jpg',
  ],
  'glamour': [
    '/Packs/Glamour-photos/Man/man1.jpg',
    '/Packs/Glamour-photos/Man/man2.jpg',
    '/Packs/Glamour-photos/Man/man3.jpg',
    '/Packs/Glamour-photos/Man/man4.jpg',
    '/Packs/Glamour-photos/Man/man5.jpg',
    '/Packs/Glamour-photos/Women/women1.jpg',
    '/Packs/Glamour-photos/Women/women2.jpg',
    '/Packs/Glamour-photos/Women/women3.jpg',
    '/Packs/Glamour-photos/Women/women4.jpg',
    '/Packs/Glamour-photos/Women/women5.jpg',
  ],
  'barbie': [
    
    '/Packs/Barbie-photos/Women/women1.jpg',
    '/Packs/Barbie-photos/Women/women2.jpg',
    '/Packs/Barbie-photos/Women/women3.jpg',
    '/Packs/Barbie-photos/Women/women4.jpg',
    '/Packs/Barbie-photos/Women/women5.jpg',
  ],
  'halloween': [
    '/Packs/Halloween-photos/Man/man1.jpg',
    '/Packs/Halloween-photos/Man/man2.jpg',
    '/Packs/Halloween-photos/Man/man3.jpg',
    '/Packs/Halloween-photos/Man/man4.jpg',
    '/Packs/Halloween-photos/Man/man5.jpg',
    '/Packs/Halloween-photos/Women/women1.jpg',
    '/Packs/Halloween-photos/Women/women2.jpg',
    '/Packs/Halloween-photos/Women/women3.jpg',
    '/Packs/Halloween-photos/Women/women4.jpg',
    '/Packs/Halloween-photos/Women/women5.jpg',
  ],
  'mythical': [
    '/Packs/Mythical-photos/Man/man1.jpg',
    '/Packs/Mythical-photos/Man/man2.jpg',
    '/Packs/Mythical-photos/Man/man3.jpg',
    '/Packs/Mythical-photos/Man/man4.jpg',
    '/Packs/Mythical-photos/Man/man5.jpg',
    '/Packs/Mythical-photos/Women/women1.jpg',
    '/Packs/Mythical-photos/Women/women2.jpg',
    '/Packs/Mythical-photos/Women/women3.jpg',
    '/Packs/Mythical-photos/Women/women4.jpg',
    '/Packs/Mythical-photos/Women/women5.jpg',
  ]
}; 